package view;

import java.awt.Cursor;
import model.DatabaseManager;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList; 
import javax.swing.filechooser.FileNameExtensionFilter; 
import java.io.InputStreamReader; 
import java.nio.file.Files; 
import java.nio.file.Paths; 
import java.net.URISyntaxException; 

public class MigratorPanel extends javax.swing.JPanel {

    // --- Suas variáveis de dependência ---
    private DatabaseManager dbManager;
    private MainAppFrame parentFrame;
    private File loadedSqlFile; // Variável para armazenar o arquivo SQL carregado
    private File currentTempRarDir; // Variável para armazenar o diretório temporário do RAR atual

    /**
     * Creates new form MigratorPanel
     */
    public MigratorPanel() {
        initComponents();
    }

    /**
     * Construtor preferido para uso programático, injetando dependências.
     * @param dbManager O gerenciador de banco de dados.
     * @param parentFrame A MainAppFrame pai para callbacks e mensagens.
     */
    public MigratorPanel(DatabaseManager dbManager, MainAppFrame parentFrame) {
        this(); // Chama o construtor padrão para que initComponents() seja executado
        this.dbManager = dbManager;
        this.parentFrame = parentFrame;
        addListeners(); // Adiciona os listeners aos componentes
        this.loadedSqlFile = null; // Inicializa a variável do arquivo carregado
        this.currentTempRarDir = null; // Inicializa a variável do diretório temporário
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelFilePath = new javax.swing.JLabel();
        jTextFieldFilePath = new javax.swing.JTextField();
        jLabelFilePath1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        jButton2.setText("Executar Migração");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/folder_magnify.png"))); // NOI18N
        jButton3.setText("Carregar Migração");

        jLabelFilePath.setText("Local:");

        jTextFieldFilePath.setEditable(false);
        jTextFieldFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilePathActionPerformed(evt);
            }
        });

        jLabelFilePath1.setText("Banco:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFilePath1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFilePath)
                            .addComponent(jTextFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilePathActionPerformed
        jTextFieldFilePath.setEditable(false);       
    }//GEN-LAST:event_jTextFieldFilePathActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

 private void addListeners() {
        // Listener para o ComboBox de seleção de banco de dados
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedDb = (String) jComboBox1.getSelectedItem();
                if (selectedDb != null && !selectedDb.isEmpty() && !selectedDb.equals("SELECIONE")) {
                    System.out.println("Banco de dados selecionado visualmente: " + selectedDb);
                } else if (selectedDb != null && selectedDb.equals("SELECIONE")) {
                    System.out.println("Opção 'SELECIONE' escolhida no combobox.");
                }
            }
        });

        // Listener para o botão "Carregar Arquivo" (jButton3)
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cleanPreviousTempRarDir(); // LIMPA O DIRETÓRIO TEMPORÁRIO ANTES DE QUALQUER NOVA SELEÇÃO
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Selecionar Arquivo SQL ou RAR");
                
                FileNameExtensionFilter sqlFilter = new FileNameExtensionFilter("Arquivos SQL (*.sql)", "sql");
                FileNameExtensionFilter rarFilter = new FileNameExtensionFilter("Arquivos RAR (*.rar)", "rar");
                
                fileChooser.addChoosableFileFilter(sqlFilter);
                fileChooser.addChoosableFileFilter(rarFilter);
                fileChooser.setAcceptAllFileFilterUsed(true); 
                fileChooser.setFileFilter(fileChooser.getAcceptAllFileFilter()); 
                
                int userSelection = fileChooser.showOpenDialog(MigratorPanel.this);

                if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File fileToLoad = fileChooser.getSelectedFile();
                    String filePath = fileToLoad.getAbsolutePath();
                    jTextFieldFilePath.setText(filePath); 

                    if (filePath.toLowerCase().endsWith(".rar")) {
                        handleRarFileSelection(fileToLoad); 
                    } else if (filePath.toLowerCase().endsWith(".sql")) {
                        loadSqlFileToTextArea(fileToLoad); 
                    } else {
                        JOptionPane.showMessageDialog(MigratorPanel.this, "Tipo de arquivo não suportado. Por favor, selecione um arquivo .sql ou .rar.", "Erro de Arquivo", JOptionPane.WARNING_MESSAGE);
                        loadedSqlFile = null; 
                        jTextFieldFilePath.setText(""); 
                        return; 
                    }

                    if (loadedSqlFile == null) {
                        jTextFieldFilePath.setText("");
                        return; 
                    }
                } else { 
                    loadedSqlFile = null; 
                    jTextFieldFilePath.setText(""); 
                    return; 
                }
            }
        });

        // Listener para o botão "Executar Script SQL" (jButton2) 
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (loadedSqlFile == null) {
                    JOptionPane.showMessageDialog(MigratorPanel.this, "Por favor, carregue um script SQL antes de executar. Use o botão 'Carregar Arquivo'.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                String selectedDbInComboBox = (String) jComboBox1.getSelectedItem();
                if (selectedDbInComboBox == null || selectedDbInComboBox.isEmpty() || selectedDbInComboBox.equals("SELECIONE")) {
                    JOptionPane.showMessageDialog(MigratorPanel.this, "Por favor, selecione um banco de dados de destino válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                final String finalCurrentDb;
                try {
                    dbManager.selectDatabase(selectedDbInComboBox);
                    finalCurrentDb = selectedDbInComboBox;
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(MigratorPanel.this, "Erro ao tentar selecionar o banco de dados '" + selectedDbInComboBox + "': " + ex.getMessage(), "Erro de Seleção de DB", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                    return;
                }
                
                final MigratorPanel panelRef = MigratorPanel.this;

                jButton2.setEnabled(false);
                jButton1.setEnabled(false); 
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

                SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        try { 
                            dbManager.executeSqlScript(loadedSqlFile, finalCurrentDb); 
                            JOptionPane.showMessageDialog(panelRef, "Script SQL executado com sucesso no DB: " + finalCurrentDb, "Sucesso", JOptionPane.INFORMATION_MESSAGE); 
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(panelRef, "Erro ao executar o script SQL: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE); 
                            ex.printStackTrace();
                            if (ex.getMessage() != null && ex.getMessage().contains("Data too long for column")) {
                                JOptionPane.showMessageDialog(panelRef, 
                                    "Atenção: Um ou mais valores são muito longos para as colunas do banco de dados. " + 
                                    "Considere aumentar o tamanho das colunas afetadas (ex: email_site) usando ALTER TABLE.", 
                                    "Sugestão de Correção", JOptionPane.INFORMATION_MESSAGE);
                            }
                        } catch (IOException ex) { 
                            JOptionPane.showMessageDialog(panelRef, "Erro ao ler o arquivo SQL: " + ex.getMessage(), "Erro de Arquivo", JOptionPane.ERROR_MESSAGE); 
                            ex.printStackTrace();
                        }
                        return null;
                    }

                    @Override
                    protected void done() {
                        jButton2.setEnabled(true);
                        jButton1.setEnabled(true); 
                        setCursor(Cursor.getDefaultCursor());
                    }
                };
                worker.execute(); 
            }
        });

        // Listener para o botão "Cancelar" (jButton1)
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int confirm = JOptionPane.showConfirmDialog(parentFrame, "Deseja realmente sair?", "Confirmar Saída", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    cleanPreviousTempRarDir(); // Limpa o diretório temporário ao sair
                    parentFrame.dispose(); 
                    if (dbManager != null) {
                        dbManager.disconnect(); 
                    }
                    System.exit(0); 
                }
            }
        });
    }

    /**
     * Método para preencher o ComboBox de bancos de dados.
     */
    public void populateDatabaseComboBox(List<String> databases) {
        jComboBox1.removeAllItems(); 
        jComboBox1.addItem("SELECIONE"); 

        if (databases != null) {
            for (String db : databases) {
                jComboBox1.addItem(db);
            }
        }
    }

    /**
     * Carrega o conteúdo de um arquivo SQL direto no JTextArea.
     * @param sqlFile O arquivo SQL a ser carregado.
     */
    private void loadSqlFileToTextArea(File sqlFile) {
        try (BufferedReader reader = new BufferedReader(new FileReader(sqlFile))) {
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append("\n");
            }
            jTextArea1.setText(sb.toString());
            loadedSqlFile = sqlFile; 
            JOptionPane.showMessageDialog(MigratorPanel.this, "Arquivo SQL carregado: " + sqlFile.getName(), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) { // <-- Conflito resolvido aqui
            JOptionPane.showMessageDialog(MigratorPanel.this, "Erro ao carregar o arquivo SQL: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            loadedSqlFile = null;
            jTextFieldFilePath.setText("");
        }
    }

    /**
     * Lida com a seleção de um arquivo RAR, listando arquivos SQL internos
     * usando um executável nativo 'Rar.exe'.
     * @param rarFile O arquivo RAR selecionado.
     */
    private void handleRarFileSelection(File rarFile) {
        File tempDir = null; // Diretório temporário para extração
        try {
            // 1. Criar um diretório temporário para extração
            tempDir = Files.createTempDirectory("rar_temp_").toFile(); 
            tempDir.deleteOnExit(); // Tenta deletar ao sair da JVM (fallback)
            this.currentTempRarDir = tempDir; // Armazena a referência para limpeza manual

            // 2. Determinar o comando 'Rar.exe' para o sistema operacional e sua localização
            String rarExecName = "Rar.exe"; 
            String os = System.getProperty("os.name").toLowerCase();
            
            // Obter o diretório onde o JAR da aplicação está rodando (ex: ".../dist/")
            File jarFileLocation = new File(MainAppFrame.class.getProtectionDomain().getCodeSource().getLocation().toURI());
            File appRootDirectory = jarFileLocation.getParentFile(); // Isso deve ser a pasta 'dist'

            // Caminho para a pasta 'lib' dentro do diretório raiz da aplicação (dist/lib)
            File libDir = new File(appRootDirectory, "lib"); 
            String rarFullPath = null; 

            File rarExeFile = new File(libDir, rarExecName);

            if (os.contains("win") && rarExeFile.exists()) {
                rarFullPath = rarExeFile.getAbsolutePath();
            } else if (os.contains("win")) { 
                rarFullPath = rarExecName; 
            } else { // macOS, Linux
                rarExecName = "rar"; 
                File rarFileLinuxMac = new File(libDir, rarExecName);
                if (rarFileLinuxMac.exists()) {
                    rarFullPath = rarFileLinuxMac.getAbsolutePath();
                } else {
                    rarFullPath = rarExecName; 
                }
            }
            
            if (rarFullPath == null) { 
                 JOptionPane.showMessageDialog(MigratorPanel.this, 
                    "Erro: Executável 'Rar.exe' (ou 'rar') não encontrado.\n" +
                    "Por favor, coloque 'Rar.exe' (no Windows) ou 'rar' (no Linux/macOS) " +
                    "dentro da pasta 'lib' na raiz da sua aplicação ou certifique-se de que está no PATH do sistema.", 
                    "Erro de Executável Rar", JOptionPane.ERROR_MESSAGE);
                loadedSqlFile = null;
                jTextFieldFilePath.setText("");
                return;
            }

            // Construir o comando para extrair o RAR
            String[] command = {rarFullPath, "x", "-p-", "-o+", rarFile.getAbsolutePath(), tempDir.getAbsolutePath()};
            
            ProcessBuilder pb = new ProcessBuilder(command);
            pb.redirectErrorStream(true); 
            pb.directory(libDir); 

            Process process = pb.start();

            // Ler a saída do processo (para depuração e feedback)
            StringBuilder output = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    output.append(line).append("\n");
                }
            }

            int exitCode = process.waitFor(); 
            System.out.println("Comando Rar.exe executado. Saída:\n" + output.toString());
            System.out.println("Exit Code: " + exitCode);

            if (exitCode != 0) {
                JOptionPane.showMessageDialog(MigratorPanel.this, 
                    "Erro ao descompactar o arquivo RAR (Exit Code: " + exitCode + ").\n" +
                    "Verifique se o executável '" + rarExecName + "' está na pasta 'lib' e se o arquivo RAR não está corrompido/protegido.\n" +
                    "Detalhes: " + output.toString().substring(0, Math.min(output.length(), 200)) + "...", 
                    "Erro de Descompactação RAR", JOptionPane.ERROR_MESSAGE);
                loadedSqlFile = null;
                jTextFieldFilePath.setText("");
                return;
            }

            // 3. Listar arquivos SQL na pasta temporária (agora que está descompactado)
            List<String> sqlFilesInsideRar = new ArrayList<>();
            // CHAMA O MÉTODO RECURSIVO PARA ENCONTRAR TODOS OS .SQL DENTRO DO TEMPDIR
            listSqlFilesInDirectory(tempDir, sqlFilesInsideRar, ""); 

            if (sqlFilesInsideRar.isEmpty()) {
                JOptionPane.showMessageDialog(MigratorPanel.this, "Nenhum arquivo .sql encontrado dentro do arquivo RAR selecionado (mesmo em subpastas ou após descompactação).", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                loadedSqlFile = null; 
                jTextFieldFilePath.setText(""); 
                return;
            }

            // 4. Mostrar seleção ao usuário
            JComboBox<String> internalSqlComboBox = new JComboBox<>(sqlFilesInsideRar.toArray(new String[0]));
            JPanel panel = new JPanel();
            panel.add(new JLabel("Selecione o arquivo SQL dentro do RAR:"));
            panel.add(internalSqlComboBox);

            int result = JOptionPane.showConfirmDialog(MigratorPanel.this, panel, "Selecionar SQL do RAR", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (result == JOptionPane.OK_OPTION) {
                String selectedSqlRelativePath = (String) internalSqlComboBox.getSelectedItem(); // Caminho relativo (ex: "pasta/arquivo.sql")
                if (selectedSqlRelativePath != null) {
                    // CONSTRÓI O CAMINHO ABSOLUTO CORRETO PARA O ARQUIVO EXTRAÍDO
                    // Este é o ponto chave: a forma como o File é construído
                    File extractedSqlFile = new File(tempDir, selectedSqlRelativePath.replace("\\", File.separator)); // Garante separadores corretos
                    
                    if (!extractedSqlFile.exists() || extractedSqlFile.isDirectory()) { // Adiciona verificação de existência
                        JOptionPane.showMessageDialog(MigratorPanel.this, 
                                "Erro: O arquivo SQL selecionado não foi encontrado ou não é um arquivo válido no diretório temporário após a extração.",
                                "Erro de Arquivo", JOptionPane.ERROR_MESSAGE);
                        loadedSqlFile = null;
                        jTextFieldFilePath.setText("");
                        return;
                    }

                    loadSqlFileToTextArea(extractedSqlFile); 

                    jTextFieldFilePath.setText(rarFile.getAbsolutePath() + " -> " + selectedSqlRelativePath);

                    JOptionPane.showMessageDialog(MigratorPanel.this, "Arquivo '" + selectedSqlRelativePath + "' do RAR carregado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    loadedSqlFile = null;
                    jTextFieldFilePath.setText("");
                }
            } else {
                jTextFieldFilePath.setText("");
                loadedSqlFile = null; 
            }

        } catch (IOException | InterruptedException | URISyntaxException ex) { 
            JOptionPane.showMessageDialog(MigratorPanel.this, "Erro inesperado ao descompactar ou processar o RAR: " + ex.getMessage(), "Erro de Operação RAR", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            loadedSqlFile = null;
            jTextFieldFilePath.setText("");
        } finally {
            // A limpeza agora é feita por cleanPreviousTempRarDir()
            // deleteDirectory(tempDir); // REMOVIDO: Não deleta aqui para evitar exclusão prematura
        }
    }

    /**
     * Lista recursivamente arquivos .sql dentro de um diretório.
     * @param directory O diretório para escanear.
     * @param sqlFilesList A lista para adicionar os caminhos relativos dos arquivos SQL.
     * @param parentPath O caminho pai relativo para os arquivos.
     */
    private void listSqlFilesInDirectory(File directory, List<String> sqlFilesList, String parentPath) {
        File[] files = directory.listFiles();
        if (files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    listSqlFilesInDirectory(file, sqlFilesList, parentPath + file.getName() + File.separator);
                } else if (file.getName().toLowerCase().endsWith(".sql")) {
                    sqlFilesList.add(parentPath + file.getName());
                }
            }
        }
    }

    /**
     * Deleta um diretório e todo o seu conteúdo recursivamente.
     * Usado para limpar diretórios temporários.
     * @param directory O diretório a ser deletado.
     */
    private void deleteDirectory(File directory) {
        if (directory == null || !directory.exists()) {
            return; // Nada para deletar
        }
        if (directory.isDirectory()) {
            File[] files = directory.listFiles();
            if (files != null) {
                for (File file : files) {
                    deleteDirectory(file);
                }
            }
        }
        directory.delete();
    }
    
    /**
     * Limpa o diretório temporário do RAR da operação anterior, se existir.
     */
    private void cleanPreviousTempRarDir() {
        if (this.currentTempRarDir != null && this.currentTempRarDir.exists()) {
            System.out.println("Limpando diretório temporário anterior: " + this.currentTempRarDir.getAbsolutePath());
            deleteDirectory(this.currentTempRarDir);
        }
        this.currentTempRarDir = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFilePath;
    private javax.swing.JLabel jLabelFilePath1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldFilePath;
    // End of variables declaration//GEN-END:variables
}
